version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile

    # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8002:8000

